---
title: "Data Repository Index"
linkTitle: "Index"
description:
menu: main
weight: -230
---

[A](#a) [B](#b) [C](#c) [D](#d) [E](#e) [F](#f) [G](#g) [H](#h) [I](#i) [J](#j) 
[K](#k) [L](#l) [M](#m) [N](#n) [O](#o) [P](#p) [Q](#q) [R](#r) [S](#s) [T](#t) 
[U](#u) [V](#v) [W](#w) [X](#x) [Y](#y) [Z](#z)

### # #

[**500 Cities: Local Data for Better Health**](/500-cities)  
<font size="2">`health behaviors` `health indicators` `health outcomes` `health services`</font> 

### A

[**American Community Survey**](/acs)  
<font size="2">`economic` `housing` `social`</font> 

[**Air Quality Data and Tools**](/air-quality)  
<font size="2">`environmental`</font> 

[**Area Health Resources Files**](/ahrf)  
<font size="2">`health services`</font> 

## B

[**BRFSS (CDC)**](https://www.cdc.gov/brfss/smart/Smart_data.htm)

* **publisher:** CDC
* **data year:** 2016
* **tags:** health behaviors
* **scale:** county, state

[**BRFSS (ISDH)**](https://www.in.gov/isdh/reports/brfss/2016/)

* **publisher:** ISDH
* **data year:** 2016
* **tags:** health behaviors
* **scale:** state

## C

[**County Health Rankings**](http://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation)

* **publisher:** University of Washington
* **data year:** variable (2018 release)
* **tags:** economic, health behaviors, health indicators, health outcomes, health services, housing, social
* **scale:** county

## E

[**Environmental Geospatial Data Gateway**](https://datagateway.nrcs.usda.gov/)

* **publisher:** NRCS (USDA) 
* **data year:** variable
* **tags:** environmental, gis
* **scale:** county, state

[**Evansville-Vanderburgh County GIS Open Data**](https://fred.stlouisfed.org/search?st=vanderburgh+county)

* **publisher:** Evanville-Vanderburgh County 
* **data year:** variable
* **tags:** economic, environmental, gis, housing, social, transportation
* **scale:** sub-county, county

## F

[**Food Environment Atlas**](https://www.ers.usda.gov/data-products/food-environment-atlas/go-to-the-atlas/)

* **publisher:** ERS (USDA) 
* **data year:** variable
* **tags:** economic, health behaviors, social
* **scale:** county

[**FRED Economic Data**](https://fred.stlouisfed.org/search?st=vanderburgh+county)

* **publisher:** Federal Reserve Bank of St. Louis 
* **data year:** variable
* **tags:** economic, housing, social
* **scale:** county, state, national

## H

[**Health Professional Shortage Areas**](https://data.hrsa.gov/data/download)

* **publisher:** HRSA
* **data year:** 2017
* **tags:** health services
* **scale:** sub-county, county

[**Hospital Discharge Data Files**](https://www.in.gov/isdh/20624.htm)

* **publisher:** ISDH
* **data year:** 2017
* **tags:** health services, health outcomes
* **scale:** state

## I

[**Indiana Data Hub**](https://hub.mph.in.gov/)

* **publisher:** Indiana 
* **data year:** variable
* **tags:** economic, health indicators, health outcomes, health services, social, transportation
* **scale:** county, state

[**Indiana (Health) Indicators**](http://indianaindicators.org)

* **publisher:** IBRC (IU) 
* **data year:** variable
* **tags:** births, deaths, infant deaths
* **scale:** state, national

[**Indiana (Health) Statistics Explorer**](https://gis.in.gov/apps/isdh/meta/stats_layers.htm)

* **publisher:** ISDH
* **data year:** variable
* **tags:** births, deaths, health indicators, health outcomes, health services, infant deaths
* **scale:** county, state

[**IPUMS: NHGIS**](https://www.nhgis.org/)

* **publisher:** University of Minnesota
* **data year:** variable
* **tags:** economic, gis, housing, social
* **scale:** sub-county, county, state, national

## M

[**Management Performance Hub (Indiana)**](https://www.in.gov/mph/index.htm)

* **publisher:** Indiana 
* **data year:** variable
* **tags:** economic, health indicators, social
* **scale:** county, state

## N

[**National Emissions Inventory**](https://www.epa.gov/air-emissions-inventories/national-emissions-inventory-nei)

* **publisher:** EPA
* **data year:** 2017
* **tags:** environmental
* **scale:** county, state, national

## T

[**TIGER Products**](https://www.census.gov/geo/maps-data/data/tiger.html)

* **publisher:** Census Bureau
* **data year:** 2017
* **tags:** gis
* **scale:** sub-county, county, state, national

## W

[**WONDER (CDC)**](https://wonder.cdc.gov/)

* **publisher:** CDC
* **data year:** variable
* **tags:** births, deaths, infant deaths
* **scale:** county, state, national